name: "Test ROCm - HIP-1"
on:
  schedule:
    - cron: "0 23 * * 0" # Sunday at 23:00 UTC
  workflow_dispatch:
jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
    with:
      spread-params-extra: ${{ vars.ROCM_HIP1_PACKAGES }}
  parse-results:
    needs:
      - run-tests
    uses: ./.github/workflows/parse-results.yml
    secrets: inherit
    with:
      spread-results-artifact-id: ${{ needs.run-tests.outputs.spread-results-artifact-id }}
